v0.4.0
withstudiocms/ui pull request #36
Opened 2024-12-25 19:48 UTC by louisescher

#### Description

This is the WIP PR for v0.4.0 of StudioCMS UI. Changes include:
- Two new color variations, `info` and `monochrome`
- Multiple new components
    - Badges
    - Groups
    - Progress Bars / Rings
    - Accordion (closes #21)
    - Sidebars (already added, just need to be documented)
- New customization options
    - Ability to pass stylesheet to integration which gets included after the main CSS file for customizing the CSS variables
    - The ability to bring your own icon set
- Updates to the documentation
    - Documentation for the new components
    - Documentation on customizing StudioCMS UI
    - Documentation on how theming works
    - Recipes
        - Login Form
        - Theme Select Dropdown
- All components and their imports being moved to virtual modules
- All components being refactored such that necessary CSS and scripts live in their own files

2024-12-25 19:56 UTC, louisescher commented
I've noticed the following things in the preview:
- JS doesn't work in prod
- Modals don't have a closing animation anymore

2025-01-16 20:09 UTC, Adammatthiesen requested changes

2025-01-16 20:09 UTC, Adammatthiesen commented on packages/studiocms_ui/src/integration.ts
> +					entrypoint: '@studiocms/ui/toolbar',
```suggestion
					entrypoint: resolve('./toolbar/index.ts'),
```
Should be using resolver when possible to prevent a issue when the UI lib is used as a dep of a dep :sweat_smile:

2025-01-22 02:40 UTC, Adammatthiesen approved these changes

2025-01-23 07:18 UTC, merged